### ISSUE TITLE
Echoing with a ' throws error

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#251] opened 2015-07-16 06:16 UTC
When I issue `/bot echo te'st`, the bot throws the following error (from staging branch):

2015-07-16 08:12:43,445 - root - ERROR - CommandDispatcher.run: convecho
Traceback (most recent call last):
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/commands.py", line 54, in run
    yield from func(bot, event, *args, **kwds)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 84, in coro
    res = func(*args, **kw)
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/plugins/default.py", line 49, in convecho
    posix_args = get_posix_args(args)
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/plugins/default.py", line 25, in get_posix_args
    posix_args = list(lexer)
  File "/usr/lib/python3.4/shlex.py", line 266, in __next__
    token = self.get_token()
  File "/usr/lib/python3.4/shlex.py", line 93, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.4/shlex.py", line 169, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

**Comment by endofline** [comment] 2015-07-16 06:20
This is expected behaviour with posix-style processing, either escape the apostrophe with a backslash or enclose the text with double-quotes. These alternate forms will work:
```
/bot echo "te'st"
/bot echo te\'st
```

**Comment by nylonee** [comment] 2015-07-16 06:26
It should not be throwing a plugin-level uncaught error either way. This needs to be patched

**Comment by endofline** [comment] 2015-07-16 06:32
Patch restores default behaviour to `/bot echo` command

**Comment by endofline** [comment] 2015-07-16 06:37
Note that raising a plugin level error from `convecho` is a **mandatory** constraint as it is intended to be a low-level function that can be used by other functions via `yield from command.run` - in this case, trapping the errors should be coded by the developer making use of the function via this method.

**Comment by nylonee** [comment] 2015-07-16 06:39
Not sure if the patch restored default behavior, I now get this error (from the handle_command instead):

2015-07-16 08:37:23,610 - root - ERROR - No closing quotation
Traceback (most recent call last):
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/handlers.py", line 141, in handle_command
    line_args = shlex.split(event.text, posix=False)
  File "/usr/lib/python3.4/shlex.py", line 276, in split
    return list(lex)
  File "/usr/lib/python3.4/shlex.py", line 266, in __next__
    token = self.get_token()
  File "/usr/lib/python3.4/shlex.py", line 93, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.4/shlex.py", line 169, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

**Comment by endofline** [comment] 2015-07-16 06:40
Can u specify your command? This error is an old error that has always been there since xmikosbot. Methinks you're seeing it now because you are running the exception to stdout plugin.

**Comment by nylonee** [comment] 2015-07-16 06:48
`/bot echo 'test` is causing the issue for me

**Comment by endofline** [comment] 2015-07-16 06:51
The latest reported issue is a different bug, and is present on bots < 2.5 - further investigation required and possibly in a separate issue.

**Comment by endofline** [comment] 2015-07-16 07:07
See #252 for further elaboration on the problem. This issue will be closed as the patch emulates the behaviour `/bot echo` on bots older than 2.5

**Closed** 2015-07-30 10:35 UTC
Labels: bug
