### ISSUE TITLE
Tldr : select entry to restitute

### ISSUE THREAD

**Issue by nimbusparis** [hangoutsbot/hangoutsbot#323] opened 2015-08-16 10:57 UTC
Plugin Tldr is good to store usual sentences to restitute to audience, it is possible to store many sentences BUT, you cannot restitute one of them (en not all).
it would be good to enhence this plugin to allow that.

**Comment by endofline** [comment] 2015-08-17 01:09
I think this might be a duplicate of #310

**Comment by endofline** [comment] 2015-08-17 10:46
In the later versions of this plugin, you can use '/bot tldr <number>' with `<number>` starting from 1 - [Plugin List](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-List) updated

**Comment by endofline** [comment] 2015-08-17 10:48
Added and confirmed in #331

**Comment by thannemann** [comment] 2015-08-18 00:16
not sure if this was changed/fixed in 2.7.2 but on 2.7.1 (current Master) you can program multiple tldr's and delete them using the number ie. /bot tldr clear 2  but using /bot tldr clear2   will clear all it doesnt error out on the number index not seperated from the clear command.

**Comment by endofline** [comment] 2015-08-18 00:56
@thannemann that sounds like a new bug but not related to this issue, which is for review - its actually related to #310

**Comment by endofline** [comment] 2015-08-18 01:03
@thannemann, the bug has been resolved in staging branch, re: #332

**Closed** 2015-08-21 06:19 UTC
Labels: enhancement, help wanted, plugin
